START: FASTQ # FASTQ, BAM, COUNT, RNK

# FASTQ_START
PAIR_END: False  # True/False
ADAPTORS: workflow/resources/adapters/merged.fa
STRAND: [0, 1, 2]  # can input [0, 1, 2] to get all possible results, then workflow auto inferrs the correct one # [2] if you know it's reverse, [1] if you know it's forward, [0] if you know it's un-stranded

# BAM_START
ALIGNER: STAR  # HISAT2, STAR

GENOME: /pi/mccb-umw/shared/OneStopRNAseq/genome/mm10_ensembl/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa
GTF: /pi/mccb-umw/shared/OneStopRNAseq/genome/mm10_ensembl/Mus_musculus.GRCm39.111.gtf
ANNO_TAB:  https://raw.githubusercontent.com/radio1988/OneStopRNAseq/dev/snakemake/workflow/resources/anno_tables/mm10.ensembl.GRCm39.111.anno.txt

MODE: strict # strict/liberal: multiple-mapping, fragment-size range
INTRON: False # True/False: count intron reads or not

# DESeq2
DESEQ2_ANALYSIS: True
MAX_FDR: 0.05
MIN_LFC: 0.585 
META: meta/meta.csv
CONTRAST_DE: meta/contrast.csv
cooksCutoff: 'FALSE'
independentFilter: 'FALSE'
blackSamples: 'sampleXXXXX,sampleYYY' # list of sample names to remove as outlier, e.g. KO_D0_1_S2, excluded in DESeq2 analysis only, optional

# GSEA
GSEA_ANALYSIS: True
GSEA_NPLOTS: 10
GSEA_PLOT_SVG: True  
GSEA_DB_PATH: workflow/resources/gsea_db/mus_musculus/test

# COUNT_START
COUNT_FILE: meta/COUNT.xlsx 

# RNK_START
RNKS:
  - /home/rui.li-umw/osr/config/config.mm10.fastq.pe.yaml
  - name2.rnk.txt  # under ./meta/name2.rnk.txt


## Optinoal Analyses ## 

# rMATs
RMATS_ANALYSIS: True
RMATS_STRANDNESS:
  {0 : fr-unstranded,
  1 : fr-firststrand, 
  2 : fr-secondstrand}

# DEXSeq analysis
DEXSEQ_ANALYSIS: True
MIN_GENE_COUNT: 100  # genes with less reads per sample will be removed from DEXSeq analysis, default 100, test with 10

CONTRAST_AS: meta/contrast.csv

# TE analysis (SalmonTE)
TE_ANALYSIS: True # True, include TE analysis in DESeq2 results (only if FASTQ provided); False, skip
TE_REFERENCE: mm # mm, hs, dm, dr (mouse, human, fruitfly,zebra-fish)

# For ASE
ASE_ANALYSIS: False
VCF: example_data/genome/mm10_chr19/BALB_cJ.mgp.v5.indels.dbSNP142.normed.chr.vcf

# CUFFLINKS
ASSEMBLY_ANALYSIS: True

# WEBSITE maintenance parameters
#MAX_FASTQ_SIZE: 1000 # Unit GB. The size of all fastq files summed must be smaller than this
CleanUpRNAseqQC: True
CleanUpRNAseqCorrection: True
