SAMPLES:
    - KO_D0_1_S2
    - KO_D0_2_S8
    - KO_D2_1_S4
    - KO_D2_2_S10
    - KO_D8_1_S6
    - KO_D8_2_S12
    - WT_D0_1_S1
    - WT_D0_2_S7
    - WT_D2_1_S3
    - WT_D2_2_S9
    - WT_D8_1_S5
    - WT_D8_2_S11

ADAPTORS: workflow/resources/adapters/merged.fa
ALIGNER: STAR  # HISAT2, STAR

PAIR_END: True

GENOME: /project/umw_mccb/genome/Mus_musculus_UCSC_mm10/mm10.ucsc.fa

INDEX: /project/umw_mccb/genome/Mus_musculus_UCSC_mm10/star_idx

GTF: /project/umw_mccb/genome/Mus_musculus_UCSC_mm10/gencode.vM25.primary_assembly.annotation.gtf

ANNO_TAB: https://raw.githubusercontent.com/radio1988/OneStopRNAseq/master/snakemake/envs/anno_tables/hg38.gencode.v34.te_included.anno.txt

STRAND: [0, 1, 2]

MODE: strict

INTRON: true

START: RNK

COUNT_FILE: meta/COUNT.txt

RNKS:
    - name1.rnk.txt

# DEG analysis
DESEQ2_ANALYSIS: False
MAX_FDR: 0.05
MIN_LFC: 0.585
META: meta/meta.xlsx
CONTRAST_DE: meta/contrast.de.xlsx
cooksCutoff: 'TRUE'
independentFilter: 'FALSE'

# TE analysis with SalmonTE
TE_ANALYSIS: False
TE_REFERENCE: mm

# Alternative Splicing Analysis (DAS)
RMATS_ANALYSIS: False
CONTRAST_AS: meta/contrast.as.xlsx
RMATS_STRANDNESS:
    {0 : fr-unstranded,
    1 : fr-firststrand,
    2 : fr-secondstrand}

# DEXSeq analysis
DEXSEQ_ANALYSIS: False
MIN_GENE_COUNT: 100

# Allele Specific Analysis
ASE_ANALYSIS: False
VCF: example_data/genome/mm10_chr19/BALB_cJ.mgp.v5.indels.dbSNP142.normed.chr.vcf

#GSEA
GSEA_ANALYSIS: True
GSEA_NPLOTS: 10
GSEA_PLOT_SVG: False
GSEA_DB_PATH: workflow/resources/gsea_db/mus_musculus/test
ASSEMBLY_ANALYSIS: False
